### ISSUE TITLE
Template fails validation procedure

### ISSUE THREAD

**Issue by elevul** [vijayshinva/AzureWireGuard#3]
Hi, i'm getting this error when I try deploying it:

`{
  "deploymentStatusCode": -1,
  "stage": 6,
  "expected": true,
  "error": {
    "message": "The template deployment 'Microsoft.Template-20200928174828' is not valid according to the validation procedure. The tracking id is '9ab86e8b-7c9d-4446-a2ad-87071ba13b38'. See inner errors for details."
  },
  "subscriptionId": "subscriptionname",
  "resourceGroupName": "AzureWireguard",
  "resourceGroupLocation": "westeurope",
  "deploymentName": "Microsoft.Template-20200928174828",
  "details": {
    "code": "InvalidTemplateDeployment",
    "message": "The template deployment 'Microsoft.Template-20200928174828' is not valid according to the validation procedure. The tracking id is '9ab86e8b-7c9d-4446-a2ad-87071ba13b38'. See inner errors for details.",
    "details": [
      {
        "code": "InvalidDomainNameLabel",
        "message": "The domain name label 74a45zzbpwdgk is invalid. It must conform to the following regular expression: ^[a-z][a-z0-9-]{1,61}[a-z0-9]$.",
        "details": []
      }
    ]
  }
}`

**Comment by PhilippElhaus** [comment]
Can confirm, no longer working.

{"code":"DeploymentFailed","message":"At least one resource deployment operation failed. Please list deployment operations for details. Please see https://aka.ms/arm-deployment-operations for usage details.","details":[{"code":"VMExtensionProvisioningError","message":"VM has reported a failure when processing extension 'AzureWireGuard'. Error message: \"Enable failed: failed to get configuration: json validation error: invalid public settings JSON: fileUris.0: Does not match format 'uri'\"\r\n\r\nMore information on troubleshooting is available at https://aka.ms/VMExtensionCSELinuxTroubleshoot "}]}

**Comment by vijayshinva** [comment]
The template has been updated to use Bicep and the dependency on the storage account has been removed. The deployment steps are simplified now. Please try now.
