### ISSUE TITLE
Location flag doesn't apply

### ISSUE THREAD

**Issue by JonathanNathanson** [vijayshinva/AzureWireGuard#5]
Hi

I've tried running this with --location uksouth and it has created the resources in the default East US region. Only way I can get it to work is by modifying the bicep file instead of providing the --location flag.

Thanks

**Comment by vijayshinva** [comment]
You need to change the location in AzureWireGuard/AzureWireGuard.parameters.json. The --location flag is the location of the Azure Deployment
